platform :ios, '7.0'
inhibit_all_warnings!

pod 'TSMessages'
pod 'ReactiveCocoa'
pod 'HexColors'
pod 'GVUserDefaults'
pod 'NZAlertView'
pod 'SIAlertView'
pod 'pop'
pod 'QBImagePickerController'
pod 'TBXML'
pod 'iOS-KML-Framework'
